---
- task:
    metadata:
      name: "SSL tests"
      description: "SSL tests"

    payload:
      artifacts:
        public:
          type: directory
          path: /home/worker/artifacts
          expires: !from_now 24
      command:
        - "/bin/bash"
        - "-c"
        - "bin/checkout.sh && nss/automation/taskcluster/scripts/build.sh"
      env:
        NSS_ENABLE_TLS_1_3: !!js/undefined # override
        NSS_TESTS: "ssl"

    extra:
      treeherder:
        groupSymbol: SSL
        groupName: SSL tests
        symbol: B

  dependents:
    - ssl_cycles
